image: Visual Studio 2017
configuration: Release
before_build:
  - appveyor-retry dotnet restore
build_script:
  - dotnet build MT1
test_script:
  # OpenCover でカバレッジを計測
  - OpenCover.bat dotnet "coverage.xml"
  # Codecov へカバレッジ結果を渡す
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
